#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Word_Drop.Resource", IsApplication=true)]

namespace Word_Drop
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int A = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int B = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int C = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int D = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int E = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int F = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int G = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int grid = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int H = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int I = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int J = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int K = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int L = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int M = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Menu = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int monoandroidsplash = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int N = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int O = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int P = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Q = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int R = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int S = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int T = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int U = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int V = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Victory = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int W = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int X = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Y = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Z = 2130837534;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
